theme: jekyll-theme-minimal
logo: [https://storage.cloud.google.com/beotus.com/8fNnQCGH2M1vSzHGkEALbP6g?authuser=8]
title: [The title of your site]
description: [A short description of your site's purpose]
